### ISSUE TITLE
awk: division by zero

### ISSUE THREAD

**Issue by aaronjensen** [arzzen/git-quick-stats#16]
I'm trying to run this on any of my repos and I end up with this: 

```
Contribution stats (by author):

        total:
          insertions:    202248 (100%)
          deletions:     72015 (100%)
          files:         10782 (100%)
awk: division by zero
 input record number 18202, file
 source line number 8
```

**Comment by arzzen** [comment]
fixed in #18

**Comment by aaronjensen** [comment]
Thanks, that fixed the error, but the reporting was still wrong. Apparently it was using my overridden pretty format from my git config. To repro, add this to your gitconfig:

```
[format]
  pretty=format:%C(yellow)%h%Creset -%C(red)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset
```

You may need to hard code the format you use, or maybe temporarily unset `HOME` so it ignores the gitconfig.
